variable "public-subnet-name1" {}
variable "public-subnet-name2" {}
variable "web-alb-sg-name" {}
variable "alb-name" {}
variable "alb-name2" {}
variable "tg-name" {}
variable "vpc-name" {}
variable "tg-name2" {}
variable "private-subnet-name1" {}
variable "private-subnet-name2" {}
variable "Owner" {}
variable "CreateDate" {}