variable "domain-name" {}
variable "cdn-name" {}
variable "web_acl_name" {}
variable "alb-dns-name" {}
variable "alb-name" {}
variable "Owner" {}
variable "CreateDate" {}
variable "s3-dns-name" {}
variable "s3-id" {}